const apiBaseUrl = 'https://api.getgogi.com/api/';

export const environment = {
  production: true,
  debugLogging: false,
  version: '26.05.16.09.P', // Update this value as needed
  ordersRefreshIntervalSeconds: 20,
  slidecardRefreshIntervalSeconds: 30,
  useMockMenuApi: false,
  apiBaseUrl,
  menuReadAllApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_ReadALL`,
  menuReadBvApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Read_BV`,
  menuReadPsApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Read_PS`,
  menuCrudApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD`,
  discountsGetAllApiUrl: `${apiBaseUrl}CMSDemo/Menu/Get_All_Discounts`,
  discountsCrudApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Discounts`,
  ordersByStatusApiUrl: `${apiBaseUrl}CMSDemo/Orders/Get_OrdersbyStatus`,
  orderByIdFullApiUrl: `${apiBaseUrl}CMSDemo/Orders/Get_OrderbyOrderIdFull_HeadandDetails`,
  ordersStatusChangeApiUrl: `${apiBaseUrl}CMSDemo/Orders/Update_OrderStatus`,
  customersApiUrl: `${apiBaseUrl}CMSDemo/User/GetUserbyUserUserAll`,
  bingoSongsApiUrl: `${apiBaseUrl}Bingo/Bingo/Get_All_Songs`,
  bingoInsertSongApiUrl: `${apiBaseUrl}Bingo/Songs/Insert_NewSong`,
  bingoInsertSongsApiUrl: `${apiBaseUrl}Bingo/Songs/Insert_NewSongs_List`,
  bingoArtistTypesApiUrl: `${apiBaseUrl}Bingo/Lookups/ArtistTypes`,
  bingoGenreApiUrl: `${apiBaseUrl}Bingo/Lookups/Genre`,
  bingoTempoApiUrl: `${apiBaseUrl}Bingo/Lookups/Tempo`,
  bingoDecadeApiUrl: `${apiBaseUrl}Bingo/Lookups/Decade`,
  bingoEraApiUrl: `${apiBaseUrl}Bingo/Lookups/Era`,
  bingoStreamingEraApiUrl: `${apiBaseUrl}Bingo/Lookups/StreamingEra`,
  bingoDifficultyApiUrl: `${apiBaseUrl}Bingo/Lookups/Difficulty`,
  bingoPrintedCardsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Printed_Cards`,
  bingoPrintedCardsByCardIdApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Printed_Cards_byCardID`,
  bingoClearCalledFlagsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Clear_All_CalledFlags`,
  bingoClearCalledSongsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Clear_All_CalledSongs`,
  bingoTopCardsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Top_Cards`,
  bingoCallSongApiUrl: `${apiBaseUrl}Bingo/Bingo/Call_TheSongNumber`,
  bingoCheckGameSetupApiUrl: `${apiBaseUrl}Bingo/Bingo/Check_GameSetup`,
  bingoGetGameWinnersResultsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Game_Winners_Results`,
  bingoCheckForWinnerApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Check_ForWinner`,
  bingoCheckForWinner2LinesApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Check_ForWinner_2Lines`,
  bingoCheckForWinner4CornersApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Check_ForWinner_4Corners`,
  bingoCheckForWinnerBlackoutApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Check_ForWinner_Blackout`,
  bingoUpsertCallListWinnerApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Upsert_CallList_Winner`,
  bingoCalledSongsApiUrl: `${apiBaseUrl}Bingo/Bingo/Get_Called_Songs`,
  bingoCallListMasterApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_Master`,
  bingoCallListSongsApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_Songs_by_CallList_ID`,
  bingoCallListSongsByGciApiUrl: `${apiBaseUrl}Bingo/CallList/Get_CallList_Songs_byGCI`,
  bingoCallListSongsBy4InningApiBaseUrl: `${apiBaseUrl}Bingo/CallList/Get_Call_List_Songs_by4Inning`,
  bingoSongsCalledCalculateByGciApiBaseUrl: `${apiBaseUrl}Bingo/CallList/Get_Songs_Called_Calculate_by_GCI`,
  bingoMaxGameCardFirstCardApiBaseUrl: `${apiBaseUrl}Bingo/CallList/Get_MaxGameCard_FirstCard`,
  bingoCallListDropdownApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_DropDown`,
  bingoInsertCallListMasterApiUrl: `${apiBaseUrl}Bingo/CallList/Create_CallList_Master`,
  bingoInsertCallListSongApiUrl: `${apiBaseUrl}Bingo/CallList/Insert_CallList_Song`,
  bingoInsertCallListSongsJsonApiUrl: `${apiBaseUrl}Bingo/CallList/Add_CallList_Song_withJsonList`,
  bingoMaxCallListIdApiUrl: `${apiBaseUrl}Bingo/CallList/Get_Max_CallList_ID`,
  bingoMaxGameIdApiUrl: `${apiBaseUrl}Bingo/CallList/Get_Max_Game_ID`,
  bingoInsertGameGameNightApiUrl: `${apiBaseUrl}Bingo/CallLIst/Insert_Game_GameNight`,
  bingoCountArtistTypeApiUrl: `${apiBaseUrl}Bingo/Count/Get_Count_ArtistType`,
  bingoCountDecadeApiUrl: `${apiBaseUrl}Bingo/Count/Get_Count_Decade`,
  bingoCountEraApiUrl: `${apiBaseUrl}Bingo/Count/Get_Count_Era`,
  bingoCountGenreApiUrl: `${apiBaseUrl}Bingo/Count/Get_Count_Genre`,
  bingoCountCLIDApiUrl: `${apiBaseUrl}Bingo/CallList/Get_Count_CallListSongs_By_CLID_Inning`,
  bingoCheckSongDuplicateApiUrl: `${apiBaseUrl}Bingo/Song/Check_Song_Duplicate?useNormalized=true`,
  thumbnailApiBaseUrl: `${apiBaseUrl}ImageLoad/Images/Get_ThumbNail_Grid`,
  thumbnailApprovalApiUrl: `${apiBaseUrl}ImageLoad/Images/Update_Image_Approval`,
  thumbnailImageBaseUrl: 'https://api.getgogi.com/App_Data/UploadedImagesTN/',
  thumbnailFullImageBaseUrl: 'https://api.getgogi.com/App_Data/UploadedImages/',
  defaultLogin: 'admin', // Set your default login here
  defaultPassword: 'makemoney100' // Set your default password here
};
