const apiBaseUrl = 'https://api.getgogi.com/api/';

export const environment = {
  production: false,
  debugLogging: true,
  version: '26.04.16.T', // Update this value as needed
  ordersRefreshIntervalSeconds: 20,
  slidecardRefreshIntervalSeconds: 30,
  useMockMenuApi: false,
  apiBaseUrl,
  menuReadAllApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_ReadALL`,
  menuReadBvApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Read_BV`,
  menuReadPsApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Read_PS`,
  menuCrudApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD`,
  discountsGetAllApiUrl: `${apiBaseUrl}CMSDemo/Menu/Get_All_Discounts`,
  discountsCrudApiUrl: `${apiBaseUrl}CMSDemo/Menu/CRUD_Discounts`,
  ordersByStatusApiUrl: `${apiBaseUrl}CMSDemo/Orders/Get_OrdersbyStatus`,
  orderByIdFullApiUrl: `${apiBaseUrl}CMSDemo/Orders/Get_OrderbyOrderIdFull_HeadandDetails`,
  ordersStatusChangeApiUrl: `${apiBaseUrl}CMSDemo/Orders/Update_OrderStatus`,
  customersApiUrl: `${apiBaseUrl}CMSDemo/User/GetUserbyUserUserAll`,
  bingoSongsApiUrl: `${apiBaseUrl}Bingo/Bingo/Get_All_Songs`,
  bingoInsertSongApiUrl: `${apiBaseUrl}Bingo/Songs/Insert_NewSong`,
  bingoInsertSongsApiUrl: `${apiBaseUrl}Bingo/Songs/Insert_NewSongs_List`,
  bingoArtistTypesApiUrl: `${apiBaseUrl}Bingo/Lookups/ArtistTypes`,
  bingoGenreApiUrl: `${apiBaseUrl}Bingo/Lookups/Genre`,
  bingoTempoApiUrl: `${apiBaseUrl}Bingo/Lookups/Tempo`,
  bingoDecadeApiUrl: `${apiBaseUrl}Bingo/Lookups/Decade`,
  bingoEraApiUrl: `${apiBaseUrl}Bingo/Lookups/Era`,
  bingoStreamingEraApiUrl: `${apiBaseUrl}Bingo/Lookups/StreamingEra`,
  bingoDifficultyApiUrl: `${apiBaseUrl}Bingo/Lookups/Difficulty`,
  bingoPrintedCardsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Printed_Cards`,
  bingoPrintedCardsByCardIdApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Printed_Cards_byCardID`,
  bingoClearCalledFlagsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Clear_All_CalledFlags`,
  bingoClearCalledSongsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Clear_All_CalledSongs`,
  bingoTopCardsApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Get_Top_Cards`,
  bingoCallSongApiUrl: `${apiBaseUrl}Bingo/Bingo/Call_TheSongNumber`,
  bingoCheckForWinnerApiBaseUrl: `${apiBaseUrl}Bingo/Bingo/Check_ForWinner`,
  bingoCalledSongsApiUrl: `${apiBaseUrl}Bingo/Bingo/Get_Called_Songs`,
  bingoCallListMasterApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_Master`,
  bingoCallListSongsApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_Songs_by_CallList_ID`,
  bingoCallListDropdownApiUrl: `${apiBaseUrl}Bingo/CallList/Get_All_CallList_DropDown`,
  bingoInsertCallListMasterApiUrl: `${apiBaseUrl}Bingo/CallList/Create_CallList_Master`,
  bingoInsertCallListSongApiUrl: `${apiBaseUrl}Bingo/CallList/Insert_CallList_Song`,
  bingoInsertCallListSongsJsonApiUrl: `${apiBaseUrl}Bingo/CallList/Add_CallList_Song_withJsonList`,
  bingoMaxCallListIdApiUrl: `${apiBaseUrl}Bingo/CallList/Get_Max_CallList_ID`,
  bingoMaxGameIdApiUrl: `${apiBaseUrl}Bingo/CallList/Get_Max_Game_ID`,
  bingoInsertGameGameNightApiUrl: `${apiBaseUrl}Bingo/CallLIst/Insert_Game_GameNight`,
  thumbnailApiBaseUrl: `${apiBaseUrl}ImageLoad/Images/Get_ThumbNail_Grid`,
  thumbnailApprovalApiUrl: `${apiBaseUrl}ImageLoad/Images/Update_Image_Approval`,
  thumbnailImageBaseUrl: 'https://api.getgogi.com/App_Data/UploadedImagesTN/',
  thumbnailFullImageBaseUrl: 'https://api.getgogi.com/App_Data/UploadedImages/',
  defaultLogin: 'admin', // Set your default login here
  defaultPassword: 'makemoney100' // Set your default password here
};
