SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
AND   TABLE_NAME   IN ('CallList_Master', 'CallList_Songs')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
GO